### PR TITLE
[BlueJeans] Update to work with new moofit-recipes

### PR DESCRIPTION
**Pull request by cwhits**
sample runs for the munki and install recipes:
```
$ autopkg run -v ./BluejeansApp.munki.recipe 
Processing ./BluejeansApp.munki.recipe...
WARNING: ./BluejeansApp.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 2.10.0.218
SparkleUpdateInfoProvider: Found URL https://swdl.bluejeans.com/desktop-app/mac/2.10.0/2.10.0.218/blue.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Sun, 13 Jan 2019 23:40:41 GMT
URLDownloader: Storing new ETag header: "514bc5da53e93c34b171ccec645a11cc"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/downloads/BlueJeansApp-2.10.0.218.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename BlueJeansApp-2.10.0.218.zip
Unarchiver: Unarchived /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/downloads/BlueJeansApp-2.10.0.218.zip to /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/BlueJeansApp
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/BlueJeansApp/BlueJeans.app: valid on disk
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/BlueJeansApp/BlueJeans.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/BlueJeansApp/BlueJeans.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
DmgCreator
DmgCreator: Created dmg from /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/BlueJeansApp at /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/BlueJeansApp.dmg
MunkiImporter
MunkiImporter: Copied pkginfo to /munki/pkgsinfo/apps/BlueJeansApp/BlueJeansApp-2.10.0.plist
MunkiImporter: Copied pkg to /munki/pkgs/apps/BlueJeansApp/BlueJeansApp-2.10.0.dmg
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/receipts/BluejeansApp.munki-receipt-20190118-082505.plist

The following new items were imported into Munki:
    Name          Version  Catalogs  Pkginfo Path                                    Pkg Repo Path                                 
    ----          -------  --------  ------------                                    -------------                                 
    BlueJeansApp  2.10.0   testing   apps/BlueJeansApp/BlueJeansApp-2.10.0.plist  apps/BlueJeansApp/BlueJeansApp-2.10.0.dmg  

The following new items were downloaded:
    Download Path                                                                                                       
    -------------                                                                                                       
    /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.munki.bluejeansapp/downloads/BlueJeansApp-2.10.0.218.zip 
```

```
$ autopkg run -v ./BluejeansApp.install.recipe
Processing ./BluejeansApp.install.recipe...
WARNING: ./BluejeansApp.install.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 2.10.0.218
SparkleUpdateInfoProvider: Found URL https://swdl.bluejeans.com/desktop-app/mac/2.10.0/2.10.0.218/blue.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Sun, 13 Jan 2019 23:40:41 GMT
URLDownloader: Storing new ETag header: "514bc5da53e93c34b171ccec645a11cc"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/downloads/BlueJeansApp-2.10.0.218.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename BlueJeansApp-2.10.0.218.zip
Unarchiver: Unarchived /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/downloads/BlueJeansApp-2.10.0.218.zip to /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp/BlueJeans.app: valid on disk
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp/BlueJeans.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp/BlueJeans.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
DmgCreator
DmgCreator: Created dmg from /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp at /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp.dmg
InstallFromDMG
InstallFromDMG: Mounted disk image /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp.dmg
InstallFromDMG: Connecting
InstallFromDMG: Sending installation request
InstallFromDMG: STATUS:Copying BlueJeans.app to /Applications/BlueJeans.app
InstallFromDMG: Disconnecting
InstallFromDMG: Result: DONE
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/receipts/BluejeansApp.install-receipt-20190118-082716.plist

Items from the following disk images were successfully installed:
    Dmg Path                                                                                         
    --------                                                                                         
    /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/BlueJeansApp.dmg  

The following new items were downloaded:
    Download Path                                                                                                         
    -------------                                                                                                         
    /Users/cwhits/Library/AutoPkg/Cache/com.github.gregneagle.install.bluejeansapp/downloads/BlueJeansApp-2.10.0.218.zip 
```

### CODE REVIEW

**Comment by gregneagle** [comment]
Has this actually settled down into something manageable? Every time I look at BlueJeans that've made some major change and never for the better; it's all just juggling bad things and recombining them in different ways. I think the wisest course of action for myself is to declare bankruptcy and just remove these recipes...

**Comment by cwhits** [comment]
They came out with a .app and got rid of the PKG so I switched it to their sparklefeed. But then someone must have complained to the right person because they came out with a PKG again. 

I have a PR open with moofit to switch to the new package but I haven't tested the whole opening once as the user to prevent it from downloading/installing to ~/Applications.

**Comment by gregneagle** [comment]
Right, and the whole "ensure you are launching the App once right after installation" bit still makes it essentially impossible to mass-deploy.

**Comment by cwhits** [comment]
Just confirmed that it does that ~/Applications/BlueJeans.app install trash if you install the pkg on a fresh machine and go to a BlueJeans link without ever having opened the .app.

**Comment by gregneagle** [comment]
Sigh. For mass deployment I see no way to automate the "ensure you are launching the App once right after installation" bit in a useful way. I wish we knew what that actually accomplishes.

**Comment by cwhits** [comment]
Interestingly enough, if user A launches /Users/A/Applications/BlueJeans.app and user B subsequently logs in and goes to a BlueJeans link, it doesn't prompt them to download the app and instead launches the /Applications/BlueJeans.app that Munki installed.

**Comment by macmule** [comment]
I re-PR'd the changes for the .download as the download was failing (https://github.com/autopkg/moofit-recipes/pull/23)

Could re-PR this one too, but would be the same changes.

Launching the current download (2.12.0.423), from /Applications & trying to join a meeting as Guest did not result in any Admin prompts etc.. so looks ok

**Comment by macmule** [comment]
@gregneagle can this be re-opened?

**Comment by gregneagle** [comment]
I think I am going to Marie Condo-ize this set of recipes as they do not spark joy.

They do not result in a deployable package that meets my standards and so I don't even use these recipes any longer. They are just a burden. 

So DeprecationNotifier -- here it comes!

**Pull request closed without merging**
